#!/bin/sh
#
# Commit hook that automatically pushes received changes to other
# repositories. 
#
# To use, copy this script into your repository's .git/hooks directory
# and rename to "post-receive" and configure mirror with the
# repositories to automatically push to.
#
# Written by Kah Goh, 2012.

# This array contains the list of repository locations to push to when
# a changes are pushed into the repository. You can also use remote 
# repository names here.
mirrors=(/home/git/repo1.git /home/git/repo2.git)

refSpec=""
while read old new refName
do
    refSpec=${refSpec}"  ${refName}"
done

for repo in "${mirrors[@]}"
do
    git push ${repo} ${refSpec}
done
