#!/bin/sh
#
# Receive hook that automatically pushes received changes to other
# repositories. 
#
# To use, copy this script into your repository's .git/hooks directory
# and rename to "post-receive" and configure mirror with the
# repositories to automatically push to.
#
#   Copyright 2013, Kah Goh
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# This array contains the list of repository locations to push to when
# a changes are pushed into the repository. You can also use remote 
# repository names here.
mirrors=(/home/git/repo1.git /home/git/repo2.git)

refSpec=""
while read old new refName
do
    refSpec=${refSpec}"  ${refName}"
done

for repo in "${mirrors[@]}"
do
    git push ${repo} ${refSpec}
done
